#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     SensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SensorColor,    sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     SensorSonic,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor F = Right Back
//Motor G = Right Front
//Motor H = Left Back
//Motor I = Left Front

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous A - Right
//
// Position robot so it is parallel to the creates, go forward sensing IR is 9 at all, if found,
// back up and position robot for dumping cube in create. If not found within certain rotation, back
// up put in last create and attempt to drive up ramp using white line.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	nMotorEncoder[motorF] = 0;
	nMotorEncoder[motorG] = 0;
	nMotorEncoder[motorH] = 0;
	nMotorEncoder[motorI] = 0;
	nMotorEncoder[motorE] = 0;
	nMotorEncoder[motorC] = 0;

}

//Used to tilt the block manipulator while addressing weight distribution
void liftTo(int encTarget, int threshold, int startPower, int endPower, int tiltPower)
{
	motor[motorE] = 20;
	int encStart = nMotorEncoder[motorE];
	float rate = (startPower - endPower) / abs(encTarget - encStart);

	int encCurr = nMotorEncoder[motorE];
	int powCurr = startPower;

	bool forward = encTarget > encCurr;

	while (!(nMotorEncoder[motorE] < encTarget + threshold && !forward) && !(nMotorEncoder[motorE] > encTarget - threshold && forward))
	{

		if (nMotorEncoder[motorE] != encCurr)// && !passed) //Checks if encoder value moved and adjusts the power
		{
			powCurr += rate * abs(nMotorEncoder[motorE] - encCurr);
			encCurr = nMotorEncoder[motorE];
		}

		if (nMotorEncoder[motorE] > encTarget) //Sets the power based on direction
			motor[motorE] = powCurr * -1;
		else
			motor[motorE] = powCurr;

		if (abs(nMotorEncoder[motorE] - encStart) > 400)
		{
			motor[motorB] = tiltPower;
			motor[motorC] = tiltPower;
		}
		else
		{
			motor[motorB] = tiltPower / -5;
			motor[motorC] = tiltPower / -5;
		}
	}
}

//For condensed code, this function serves as an easy way to move all motors forward/backwards. Distance is in cm
void forward(int power, int distance)
{
	if(distance != 0)
	{
		nMotorEncoder[motorH] = 0;
		while (69 * abs(distance) > abs(nMotorEncoder[motorH]))
		{
			motor[motorF] = power;
			motor[motorG] = power;
			motor[motorH] = power;
			motor[motorI] = power;
		}
		motor[motorF] = 0;
		motor[motorG] = 0;
		motor[motorH] = 0;
		motor[motorI] = 0;
	}
	else
	{
		motor[motorF] = power;
		motor[motorG] = power;
		motor[motorH] = power;
		motor[motorI] = power;
	}
}

//For condensed code, this function serves as an easy way to turn the robot by specifing the two sides power
void turn(int powL, int powR, int distance)
{
	if(distance != 0)
	{
		nMotorEncoder[motorH] = 0;
		while (69 * abs(distance) > abs(nMotorEncoder[motorH]))
		{
			motor[motorF] = powR;
			motor[motorG] = powR;
			motor[motorH] = powL;
			motor[motorI] = powL;
		}
		motor[motorF] = 0;
		motor[motorG] = 0;
		motor[motorH] = 0;
		motor[motorI] = 0;
	}
	else
	{
		motor[motorF] = powR;
		motor[motorG] = powR;
		motor[motorH] = powL;
		motor[motorI] = powL;
	}
}

//For condensed code, this function serves as an easy way to turn the robot by specifing the two sides power.
//This one uses an encoder on the other side.
void turnL(int powL, int powR, int distance)
{
	if(distance != 0)
	{
		nMotorEncoder[motorG] = 0;
		while (69 * abs(distance) > abs(nMotorEncoder[motorG]))
		{
			motor[motorF] = powR;
			motor[motorG] = powR;
			motor[motorH] = powL;
			motor[motorI] = powL;
		}
		motor[motorF] = 0;
		motor[motorG] = 0;
		motor[motorH] = 0;
		motor[motorI] = 0;
	}
	else
	{
		motor[motorF] = powR;
		motor[motorG] = powR;
		motor[motorH] = powL;
		motor[motorI] = powL;
	}
}

void releaseBucket()
{
	nMotorEncoder[motorB] = 0;
	while(nMotorEncoder[motorB] < 52)
	{
		motor[motorB] = 67;
		motor[motorC] = 67;
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
}

task main()
{
	initializeRobot();

	waitForStart();

	bool pos1 = false;
	bool pos2 = false;
	int rotated;

	releaseBucket();

	forward(20, 1);
	//Find IR while following line
	nMotorEncoder[motorI] = 0;
	if(SensorValue(SensorIR) != 0 && SensorValue(SensorIR) != 9) //If IR is in closest, skip this part
	{
		while(SensorValue(SensorIR) != 8 && SensorValue(SensorIR) != 9 && SensorValue(SensorIR) != 0)
		{
			if(SensorValue(SensorColor) > 10)
				turn(60, 20, 0);
			else
				turn(20, 60, 0);
		}
		if(SensorValue(SensorIR) == 0 || nMotorEncoder[motorI] < 1000 )
		{
			pos2 = true;
			forward(-45, -2);
		}
		else
			forward(-45, -3);
	}
	else
		pos1 = true;
	rotated = nMotorEncoder[motorI];
	forward(0, 0);
	//Align to drop
	nMotorEncoder(motorG) = 0;
	while(SensorValue(SensorIR) != 5)
	{
		turn(-60, 60, 0);
	}

	if(pos2)
		forward(50, 33);
	else if(pos1)
	{
		turn(-60, 60, 2);
		forward(50, 35);
	}
	else
	{
		turn(-60, 60, 2);
		forward(50, 38);
	}
	forward(0, 0);

	//Drop cube
	nMotorEncoder[motorC] = 0;
	nMotorEncoder[motorE] = 0;
	liftTo(460, 25, 82, 6, 15); //Lifts steadily to encoder value 700
	motor[motorE] = 21; //Continue into stopper
	wait10Msec(130);
	motor[motorE] = 0; //Stop the lift
	while (!(nMotorEncoder[motorC] < -18)) //Dump blocks
	{
		motor[motorC] = -20;
		motor[motorB] = -20;
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait10Msec(30);
	liftTo(300, 80, 50, 10, 1);
	motor[motorE] = 0;

	//Retrace steps
	motor[motorC] = -20;
	motor[motorB] = -20;
	forward(-50, -17);
	motor[motorB] = 0;
	motor[motorC] = 0;
	forward(0, 0);
	if(!pos1 && !pos2)
	{
		turn(70, -70, 17);
		if(rotated > 3800)
		{
			PlaySound(soundUpwardTones);
			forward(20, 30);
		}
		else
		{
			PlaySound(soundDownwardTones);
			forward(20, 50);
		}

		forward(0, 0);

		turn(-60, 60, 10);
		forward(70, 70);
		turn(-60, 60, 7);
		forward(20, 30);
		turn(-30, 50, 5);
		forward(30, 63);
		motor[motorC] = -20;
		motor[motorB] = -20;
		wait10Msec(500);
		motor[motorB] = 0;
		motor[motorC] = 0;
	}
	//line up to start going to the ramp after dump in 3 or 4
	else
	{
		turn(-70, 70, 19);
		if(pos2)
		{
			turn(-70, 70, 7);
			PlaySound(soundBeepBeep);
			forward(20, 70);
		}
		else
		{
			PlaySound(soundBlip);
			forward(20, 60);
		}

		forward(0, 0);

		turnL(70, -50, 12);
		forward(60, 35);
		turnL(50, -30, 20);
		forward(20, 28);
		turnL(70, -50, 37);
		forward(30, 80);
		motor[motorC] = -20;
		motor[motorB] = -20;
		wait10Msec(500);
		motor[motorB] = 0;
		motor[motorC] = 0;
	}
}
